version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: medical_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: data_migration
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://medical_mongo:27017/medical_db
    volumes:
      - ./data:/app/data  # Mounts the local "data" folder inside the container at "/app/data"
    restart: unless-stopped

volumes:
  mongodb_data: